task: segment
mode: train
model: yolov8x-seg.pt
data: data/fixed_yamls/GI.yaml
imgsz: 320
batch: 32
optimizer: auto
lr0: 0.01
lrf: 0.01
cos_lr: false
weight_decay: 0.0005
warmup_epochs: 3
epochs: 1000
patience: 20
seed: 0
deterministic: true
name: yolo8x_GI

#Note: optimizer=auto can auto-select optimizer settings and may override some hyperparameters. We used lr0=0.01 as the paper stated, but optimizer=auto overrides it. Fortunately, it still selected lr=0.0
