task: segment
mode: train
model: yolo8x-seg.pt
data: data/fixed_yamls/GI.yaml
imgsz: 320
batch: 32
lr0: 0.01
weight_decay: 0.0005
warmup_epochs: 3
epochs: 1000
patience: 20
optimizer: auto
seed: 0
deterministic: true
project: runs
name: yolo11x_GI
